# Generated by Django 4.1 on 2022-09-07 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_id', models.IntegerField(unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('language_type', models.CharField(choices=[('p', 'python'), ('d', 'django'), ('c', 'css'), ('h', 'html'), ('b', 'bootstrap'), ('j', 'javascript')], max_length=1)),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('css_links', models.TextField()),
                ('js_links', models.TextField()),
                ('html_code', models.TextField()),
                ('css_code', models.TextField()),
                ('javascript_code', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Project', models.FileField(blank=True, null=True, upload_to='projects')),
                ('statuc', models.CharField(choices=[('d', 'Draft'), ('p', 'publish')], max_length=1)),
            ],
        ),
    ]
