# Generated by Django 4.1 on 2022-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pictuer', models.ImageField(upload_to='my_pictuer')),
                ('job', models.CharField(max_length=30)),
                ('about_my_self', models.TextField()),
            ],
        ),
    ]
